# Generated by Django 4.1.6 on 2023-06-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_id_code_user_id_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_code',
            new_name='code',
        ),
    ]
